// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleTracking.Data.TrackingHistory;

namespace VehicleTracking.Data.Migrations.TrackingHistory
{
    [DbContext(typeof(TrackingHistoryContext))]
    [Migration("20190718142424_UpdateDataTypeOfLongitudeLatitude")]
    partial class UpdateDataTypeOfLongitudeLatitude
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleTracking.Data.TrackingHistory.TrackingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal>("Lat")
                        .HasColumnType("DECIMAL(12,9)");

                    b.Property<decimal>("Lon")
                        .HasColumnType("DECIMAL(12,9)");

                    b.Property<Guid>("TrackingSessionId");

                    b.HasKey("Id");

                    b.HasIndex("TrackingSessionId");

                    b.ToTable("TrackingHistories");
                });

            modelBuilder.Entity("VehicleTracking.Data.TrackingHistory.TrackingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("TrackingRemark");

                    b.Property<Guid>("VehicleId");

                    b.HasKey("Id");

                    b.ToTable("TrackingSessions");
                });

            modelBuilder.Entity("VehicleTracking.Data.TrackingHistory.TrackingHistory", b =>
                {
                    b.HasOne("VehicleTracking.Data.TrackingHistory.TrackingSession", "TrackingSession")
                        .WithMany("TrackingHistories")
                        .HasForeignKey("TrackingSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
